-- AlterTable
ALTER TABLE `AlertRule` MODIFY `type` ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'IFOOD_ORDER', 'FINANCIAL_DUE', 'FISCAL_PENDING', 'IMPORT_ERROR', 'INTEGRATION_ERROR', 'SECURITY', 'OTHER') NOT NULL;
